# Generated by Django 6.0.2 on 2026-02-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='colegio',
            field=models.CharField(default='pendiente', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='municipio',
            field=models.CharField(default='pendiente', max_length=100),
            preserve_default=False,
        ),
    ]
