# Generated by Django 6.0.2 on 2026-02-07 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_estudiante_colegio_estudiante_municipio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='creditos',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='nota',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='periodo',
        ),
        migrations.AddField(
            model_name='nota',
            name='valor',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='nota',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='notas.estudiante'),
        ),
    ]
